language: node_js
cache: 
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - danilo@comono.co
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: d0999860-371c-4243-95bd-a6b1c412e0ee
  app: platzi-store-backend-0
  on:
    repo: darmo1/platzi-store-backend
